export type NAVIGATE_TO_PLY = 'NAVIGATE_TO_PLY';
export type NAVIGATE_TO_KEY = 'NAVIGATE_TO_KEY';
export type NAVIGATE_TO_MOVE = 'NAVIGATE_TO_MOVE';

export type GAME_SET_SETTINGS = 'GAME_SET_SETTINGS';

export type LOAD_ANALYSIS = 'LOAD_ANALYSIS';
export type ANALYSE_POSITION = 'ANALYSE_POSITION';