import * as types from './GameActionTypes';

export const NAVIGATE_TO_PLY : types.NAVIGATE_TO_PLY = 'NAVIGATE_TO_PLY';
export const NAVIGATE_TO_KEY : types.NAVIGATE_TO_KEY = 'NAVIGATE_TO_KEY';
export const NAVIGATE_TO_MOVE : types.NAVIGATE_TO_MOVE = 'NAVIGATE_TO_MOVE';

export const GAME_SET_SETTINGS : types.GAME_SET_SETTINGS = 'GAME_SET_SETTINGS';

export const LOAD_ANALYSIS : types.LOAD_ANALYSIS = 'LOAD_ANALYSIS';
export const ANALYSE_POSITION : types.ANALYSE_POSITION = 'ANALYSE_POSITION';